### ISSUE TITLE
Exponentiation

### ISSUE THREAD

**Issue by fmmanicacci** [fmmanicacci/nanograd#10]
(**Work in progress..**)

## Description

The next operation to be implemented is the exponentiation.

## Details

```math
L = x^y
```

- We can transform $L$ so that $L = e^{y\ln(x)}$, and so $L$ can be seen has a composition of the functions $\exp$ and $u$, with $u = y\ln(x)$. To compute the derivative of $L$ we use the chain rule: $\frac{dL}{dx} = \frac{dL}{du}\frac{du}{dx}$ and $\frac{dL}{dy} = \frac{dL}{du} \frac{du}{dy}$.
- $\frac{dL}{du} = e^u = e^{y\ln(x)} = x^y$
- $\frac{d}{dx}\ln(x) = \frac{1}{x}$
- $\frac{du}{dx} = \frac{d}{dx}y\ln(x) = y\frac{d}{dx}\ln(x) + \ln(x)\frac{dy}{dx} = y\times\frac{1}{x} + \ln(x)\times 0 = \frac{y}{x}$
- $\frac{du}{dy} = \frac{d}{dy}y\ln(x) = y\frac{d}{dy}\ln(x) + \ln(x)\frac{dy}{dy} = y \times 0 + \ln(x) \times 1 = \ln(x)$

Putting everything together, we get :

```math
\frac{dL}{dx} = x^y \times \frac{y}{x} = yx^{y-1}
```

```math
\frac{dL}{dy} = \ln(x)x^y
```

A special case of exponentiation is when $y = -1$, in this case $L = x^{-1} = \frac{1}{x}$. The derivative of $L$ is then equals to $\frac{dL}{dx} = -\frac{1}{x^2}$.

## TODOs

- [x] Add the operation `Operation.EXPONENTIATION` with the label `pow`
- [x] Add the operation `Operation.INVERTION` with the label `inv`
- [x] Implement the method `__pow__` and `__rpow__`
- [x] Implement the method `pow` based on `__pow__`
- [x] Implement the method `__invert__` as an unary operator
- [x] Implement the method `invert` based on `__inv__`

## Criteria acceptance

- [x] Typing
- [x] Comments
- [x] Docstrings
- [x] Unit tests
