### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by fmmanicacci** [fmmanicacci/nanograd#3]
The first operation to be implemented is the addition. Use the following information to implement the `_backward_fn` function :

1. As the node may be involved several times in the computational graph, the gradients of each operation must add up over time
2. Implement the `_backward_fn` function as a closure to capture the reference of the operands and thus update their gradients later
3. Calculus told us to multiply the gradient of each operand by the gradient of the resulting node (chain rule)

Here are the mathematical details

```math
L = x + y
```

It is important to know : 

1. $\frac{dx}{dx}$ always equals $1$
2. $\frac{dy}{dx}$ always equals $0$, if $y$ does not depend on $x$
3. $\frac{d(x + y)}{dx} = \frac{dx}{dx} + \frac{dy}{dx}$

Assuming that $x$ and $y$ are independent variables, and combining all the above facts, we obtain :

```math
\frac {dL}{dx} = \frac{d(x + y)}{dx} = \frac{dx}{dx} + \frac{dy}{dx} = 1 + 0 = 1
```
```math
\frac {dL}{dy} = \frac{d(x + y)}{dy} = \frac{dx}{dy} + \frac{dy}{dy} = 0+ 1 = 1
```

## TODOs

- [x] Add the addition to the `Operation` enumeration with a string representation equal to `add`
- [x] implement the `__add__` and `__radd__` method
   - [x] verify the type of the argument : only `int`, `float` and `Scalar` are accepted for the moment 
   - [x] each of this method must create and return a new `Scalar` object whose data equals to the sum of the two operands. Don't forget to update the `_op` and the `_prev` attributes.
   - [x] set the `_backward_fn` attribute of the newly created `Scalar` object which updates the gradient of its children following the three previous tips.
- [x] implement the `add` method, which takes an additional argument called `label` used to set the label of the new `Scalar` object. Call the `__add__` method defined earlier to perform the calculation.

## Acceptance criteria

- [x] Typing
- [x] Comment
- [x] Docstrings
- [x] Unit tests
