### ISSUE TITLE
Multiplication

### ISSUE THREAD

**Issue by fmmanicacci** [fmmanicacci/nanograd#7]
## Description

The third operation to be implemented is the multiplication.

## Details

```math
L = x \times y
```

```math
\frac{dL}{dx} = \frac{d(x \times y)}{dx} = y\frac{dx}{dx} + x\frac{dy}{dx} = y \times 1 + x \times 0 = y
```

```math
\frac{dL}{dy} = \frac{d(x \times y)}{dy} = y\frac{dx}{dy} + x\frac{dy}{dy} = y \times 0 + x \times 1 = x
```

## TODOs

- [x] add the operation `Operation.MULTIPLICATION`, with label set to `mul`
- [x] implement the `__mul__` member method
- [x] implement the `__rmul__` member method
- [x] implement the `mul` member method

## Acceptance criteria

- [x] Typing
- [x] Comments
- [x] Docstrings
- [x] Unit tests
