### ISSUE TITLE
Division

### ISSUE THREAD

**Issue by fmmanicacci** [fmmanicacci/nanograd#9]
## Description

The fourth operation to be implemented is the division.

## Details

```math
L = \frac{x}{y}
```

```math
\frac{d}{x}(\frac{1}{x}) = -\frac{1}{x^2}
```

```math
\frac{dL}{dx} = \frac{d}{dx}(\frac{x}{y}) = \frac{d}{dx}(x \times \frac{1}{y}) = x\frac{d}{dx}(\frac{1}{y}) + \frac{1}{y}\frac{dx}{dx} = x \times 0 + \frac{1}{y} \times 1 = \frac{1}{y}
```

```math
\frac{dL}{dy} = \frac{d}{dy}(\frac{x}{y}) = \frac{d}{dy}(x \times \frac{1}{y}) = x\frac{d}{dy}(\frac{1}{y}) + \frac{1}{y}\frac{dx}{dy} = x \times \frac{-1}{y^2} + \frac{1}{y} \times 0 = \frac{-x}{y^2}
```

## TODOs

- [x] add the operation `Operation.DIVISION`, with the label `div`
- [x] implement the member methods `__truediv__` and `__rtruediv__`
- [x] implement the member methods `__floordiv__` and `__rfloordiv__`
- [x] implement the member method `div`, that is based on `__truediv__`
- [x] implement the member method `floordiv`, that is based on `__floordiv__`

## Acceptance criteria

- [x] Typing
- [x] Comments
- [x] Docstrings
- [x] Unit tests
